"""add screen style

Revision ID: b7affe3d545d
Revises: c95400ac7f7d
Create Date: 2023-06-30 14:55:36.816930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7affe3d545d'
down_revision = 'c95400ac7f7d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('screen', sa.Column('name_style', sa.String(length=500), nullable=True))
    op.add_column('screen', sa.Column('time_style', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('screen', 'time_style')
    op.drop_column('screen', 'name_style')
    # ### end Alembic commands ###
