"""notice enable column

Revision ID: c95400ac7f7d
Revises: fad19aa05a7c
Create Date: 2023-06-06 12:17:44.707943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c95400ac7f7d'
down_revision = 'fad19aa05a7c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notice', sa.Column('enable', sa.Boolean(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notice', 'enable')
    # ### end Alembic commands ###
